// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'your api key',
    appId: '1:848014412192:web:bdbdb70a8c92065c0ebcc5',
    messagingSenderId: '848014412192',
    projectId: 'calorie-detective',
    authDomain: 'calorie-detective.firebaseapp.com',
    storageBucket: 'calorie-detective.firebasestorage.app',
    measurementId: 'G-MDZQMQGBNQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'your api key',
    appId: '1:848014412192:android:efe8f709fef389150ebcc5',
    messagingSenderId: '848014412192',
    projectId: 'calorie-detective',
    storageBucket: 'calorie-detective.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'your api key',
    appId: '1:848014412192:ios:4a0203a8b87ab9960ebcc5',
    messagingSenderId: '848014412192',
    projectId: 'calorie-detective',
    storageBucket: 'calorie-detective.firebasestorage.app',
    iosBundleId: 'com.example.caloriApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'your api key',
    appId: '1:848014412192:ios:4a0203a8b87ab9960ebcc5',
    messagingSenderId: '848014412192',
    projectId: 'calorie-detective',
    storageBucket: 'calorie-detective.firebasestorage.app',
    iosBundleId: 'com.example.caloriApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'your api key',
    appId: '1:848014412192:web:bfe9f062e52d971f0ebcc5',
    messagingSenderId: '848014412192',
    projectId: 'calorie-detective',
    authDomain: 'calorie-detective.firebaseapp.com',
    storageBucket: 'calorie-detective.firebasestorage.app',
    measurementId: 'G-G49R23J6FW',
  );
}